apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-sync
spec:
  project: default
  source:
    repoURL: 'https://github.com/ntorres1980/gitops-applicationsets'
    targetRevision: main
    path: 'applicationsets'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true