apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservicios-prod
spec:
  generators:
    - git:
        repoURL: 'https://github.com/ntorres1980/gitops-applicationsets'
        revision: main
        files:
          - path: 'apps/*/values-prod.yaml'
  template:
    metadata:
      name: '{{path.basename}}-prod'
    spec:
      project: prod
      source:
        repoURL: 'https://github.com/ntorres1980/gitops-applicationsets'
        targetRevision: main
        path: 'charts/microservicio'
        helm:
          valueFiles:
            - '{{path.basename}}/values-dev.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}-prod'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
