apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
spec:
  sourceRepos:
    - 'https://github.com/tuusuario/mi-repo-gitops'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
